Fase 2: Análisis Estadístico

. Análisis de variables numéricas:

- Estadísticas descriptivas (media, mediana, moda, desviación estándar, etc.) de las variables numéricas relevantes.
- Identificación de valores atípicos en las variables numéricas.
- Análisis de correlación entre variables numéricas --> se puede hacer una matriz de correlacion, por parejas, etc

.  Análisis de variables categóricas:
- Distribución de frecuencias de las variables categóricas relevantes. unic, value counts, que recuentos tengo para cada categoria

En todos los ejercicios, no te quedes solo en el “número”: añade siempre una breve interpretación en lenguaje natural, como lo haría un analista al presentar resultados a un equipo no técnico

In [30]:
import pandas as pd
import numpy as numpy
pd.set_option("display.max_columns", None)
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
df_unido = pd.read_csv("documentos_unidos.csv")

In [47]:
def exploracion_inicial(df):
    display(df.sample(5))
    print("=" * 100)
    print(df.info())
    print("=" * 100)
    print(" " * 100)

In [48]:
exploracion_inicial(df_unido)

,loyalty_number,country,province,city,postal_code,gender,education,salary,marital_status,loyalty_card,clv,enrollment_type,enrollment_year,enrollment_month,cancellation_year,cancellation_month,is_active,year,month,flights_booked,flights_with_companions,total_flights,distance,points_accumulated,points_redeemed,dollar_cost_points_redeemed
91398,304779,Canada,Ontario,Toronto,P1W 1K4,Female,High School or Below,54137,Married,Nova,15032.90,Standard,2016,1,Activo,Activo,1,2017,12,0,0,0,0,0.0,0.0,0
186559,515656,Canada,British Columbia,Vancouver,V1E 4R6,Male,Bachelor,61809,Married,Nova,4282.95,Standard,2013,12,Activo,Activo,1,2017,7,5,5,10,2170,217.0,0.0,0
274118,709724,Canada,Ontario,Trenton,K8V 4B2,Male,College,73510,Single,Aurora,29589.94,Standard,2014,9,Activo,Activo,1,2018,2,3,3,6,786,117.0,0.0,0
375719,937956,Canada,British Columbia,Vancouver,V1E 4R6,Female,Bachelor,103037,Divorced,Star,11900.54,Standard,2015,4,Activo,Activo,1,2018,8,9,8,17,4573,457.0,0.0,0
62431,240861,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,92551,Married,Nova,2824.68,Standard,2015,9,2016,5,0,2017,7,0,0,0,0,0.0,0.0,0

====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 403760 entries, 0 to 403759
Data columns (total 26 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   loyalty_number               403760 non-null  int64
 1   country                      403760 non-null  object
 2   province                     403760 non-null  object
 3   city                         403760 non-null  object
 4   postal_code                  403760 non-null  object
 5   gender                       403760 non-null  object
 6   education                    403760 non-null  object
 7   salary                       403760 non-null  int64
 8   marital_status               403760 non-null  object
 9   loyalty_card                 403760 non-null  object
 10  clv                          403760 non-null  float64
 11  enrollment_type              403760 non-null  object
 12  enrollment_year              403760 non-null  int64
 13  enrollment_month             403760 non-null  int64
 14  cancellation_year            403760 non-null  object
 15  cancellation_month           403760 non-null  object
 16  is_active                    403760 non-null  int64
 17  year                         403760 non-null  int64
 18  month                        403760 non-null  int64
 19  flights_booked               403760 non-null  int64
 20  flights_with_companions      403760 non-null  int64
 21  total_flights                403760 non-null  int64
 22  distance                     403760 non-null  int64
 23  points_accumulated           403760 non-null  float64
 24  points_redeemed              403760 non-null  float64
 25  dollar_cost_points_redeemed  403760 non-null  int64
dtypes: float64(3), int64(12), object(11)
memory usage: 80.1+ MB
None
====================================================================================================

In [49]:
print(df_unido.duplicated().sum())

0

In [50]:
# numericas

df_unido.describe(include="number").T

,count,mean,std,min,25%,50%,75%,max
loyalty_number,403760.0,549875.383713,258961.514684,100018.00,326699.00,550598.00,772152.00,999986.00
salary,403760.0,77932.277863,30076.538315,15609.00,64001.00,73510.00,82940.00,407228.00
clv,403760.0,7990.864857,6863.317160,1898.01,3981.78,5776.34,8937.12,83325.38
enrollment_year,403760.0,2015.250716,1.979427,2012.00,2014.00,2015.00,2017.00,2018.00
enrollment_month,403760.0,6.667555,3.398829,1.00,4.00,7.00,10.00,12.00
is_active,403760.0,0.877031,0.328402,0.00,1.00,1.00,1.00,1.00
year,403760.0,2017.500352,0.500000,2017.00,2017.00,2018.00,2018.00,2018.00
month,403760.0,6.501335,3.451982,1.00,4.00,7.00,10.00,12.00
flights_booked,403760.0,4.134050,5.230064,0.00,0.00,1.00,8.00,21.00
flights_with_companions,403760.0,1.036569,2.080472,0.00,0.00,0.00,1.00,11.00
total_flights,403760.0,5.170619,6.526858,0.00,0.00,1.00,10.00,32.00
distance,403760.0,1214.460979,1434.098521,0.00,0.00,525.00,2342.00,6293.00
points_accumulated,403760.0,124.263761,146.696179,0.00,0.00,53.00,240.00,676.50
points_redeemed,403760.0,30.838587,125.758002,0.00,0.00,0.00,0.00,876.00
dollar_cost_points_redeemed,403760.0,2.495973,10.172033,0.00,0.00,0.00,0.00,71.00

In [54]:
df_median = df_unido[num_cols].median()
df_mode = df_unido[num_cols].mode().iloc[0]

In [55]:
df_median

loyalty_number                 550598.00
salary                          73510.00
clv                              5776.34
enrollment_year                  2015.00
enrollment_month                    7.00
is_active                           1.00
year                             2018.00
month                               7.00
flights_booked                      1.00
flights_with_companions             0.00
total_flights                       1.00
distance                          525.00
points_accumulated                 53.00
points_redeemed                     0.00
dollar_cost_points_redeemed         0.00
dtype: float64

In [56]:
df_mode

loyalty_number                 617489.00
salary                          73510.00
clv                              8564.77
enrollment_year                  2018.00
enrollment_month                    5.00
is_active                           1.00
year                             2018.00
month                              11.00
flights_booked                      0.00
flights_with_companions             0.00
total_flights                       0.00
distance                            0.00
points_accumulated                  0.00
points_redeemed                     0.00
dollar_cost_points_redeemed         0.00
Name: 0, dtype: float64

In [43]:
variable_economica = ['salary', 'clv']

for col in variable_economica:
    print(f"\nAnálisis de {col}")
    print(df_unido[col].describe(percentiles=[0.5, 0.75, 0.9, 0.95, 0.99]))

Análisis de salary
count    403760.000000
mean      77932.277863
std       30076.538315
min       15609.000000
50%       73510.000000
75%       82940.000000
90%       98892.000000
95%      106899.000000
99%      239867.000000
max      407228.000000
Name: salary, dtype: float64

Análisis de clv
count    403760.000000
mean       7990.864857
std        6863.317160
min        1898.010000
50%        5776.340000
75%        8937.120000
90%       15363.850000
95%       22041.860000
99%       35944.710000
max       83325.380000
Name: clv, dtype: float64

In [37]:
# categóricas

df_unido.describe(include="object").T

                     count unique       top    freq
country             403760      1    Canada  403760
province            403760     11   Ontario  130258
city                403760     29   Toronto   80775
postal_code         403760     55   V6E 3D9   21944
gender              403760      2    Female  202757
education           403760      5  Bachelor  252567
marital_status      403760      3   Married  234845
loyalty_card        403760      3      Star  183745
enrollment_type     403760      2  Standard  380419
cancellation_year   403760      7    Activo  354110
cancellation_month  403760     13    Activo  354110

In [38]:
df_unido.select_dtypes(include=["object", "category"]).columns

Index(['country', 'province', 'city', 'postal_code', 'gender', 'education',
       'marital_status', 'loyalty_card', 'enrollment_type',
       'cancellation_year', 'cancellation_month'],
      dtype='object')

In [41]:
categorical_cols = df_unido.select_dtypes(include=["object", "category"]).columns

for col in categorical_cols:
    print(f"\n### Distribución de {col}")
    print(df_unido[col].value_counts(dropna=False))

### Distribución de country
country
Canada    403760
Name: count, dtype: int64

### Distribución de province
province
Ontario                 130258
British Columbia        106442
Quebec                   79573
Alberta                  23360
Manitoba                 15900
New Brunswick            15352
Nova Scotia              12507
Saskatchewan              9861
Newfoundland              6244
Yukon                     2679
Prince Edward Island      1584
Name: count, dtype: int64

### Distribución de city
city
Toronto           80775
Vancouver         62314
Montreal          49687
Winnipeg          15900
Whistler          13994
Halifax           12507
Ottawa            12262
Edmonton          11768
Trenton           11710
Quebec City       11698
Dawson Creek      10725
Fredericton       10266
Regina             9861
Kingston           9652
Tremblant          9576
Victoria           9444
Hull               8612
West Vancouver     7831
St. John's         6244
Thunder Bay        6171
Sudbury            5493
Moncton            5086
Calgary            4584
Banff              4296
London             4195
Peace River        2712
Whitehorse         2679
Kelowna            2134
Charlottetown      1584
Name: count, dtype: int64

### Distribución de postal_code
postal_code
V6E 3D9    21944
V5R 1W3    16529
V6T 1Y8    13994
V6E 3Z3    13128
M2M 7K8    12855
P1J 8T7    12093
H2T 9K8    12000
K8V 4B2    11710
G1B 3L5    11698
H2T 2J6    10747
U5I 4F1    10725
V1E 4R6    10713
E3B 2H2    10266
R2C 0M5    10059
M9K 2P4     9652
H5Y 2S9     9576
V10 6T5     9444
K1F 2R2     9375
H2Y 2W2     8824
J8Y 3Z5     8612
M8Y 4K8     8207
H4G 3T4     8184
B3J 9S2     7952
V6V 8Z3     7831
P2T 6G3     7790
H2Y 4R4     7623
M1R 4K3     7533
P1L 8X8     6790
P1W 1K4     6604
T9G 1W3     6430
A1C 6H9     6244
K8T 5M5     6171
M2Z 4K1     6168
P5S 6R4     5925
M5V 1G5     5493
S6J 3G0     5437
T3G 6Y6     5338
E1A 2A7     5086
T3E 2V9     4584
B3C 2M8     4555
S1J 3C5     4424
T4V 1D4     4296
M5B 3E4     4195
M2M 6J7     3693
R6Y 4T5     3441
M2P 4F6     3045
K1G 4Z0     2887
T9O 2W2     2712
Y2K 6R0     2679
R3R 3T4     2400
H3T 8L4     2141
V09 2E9     2134
C1A 6E8     1584
H3J 5I6      168
M3R 4K8       72
Name: count, dtype: int64

### Distribución de gender
gender
Female    202757
Male      201003
Name: count, dtype: int64

### Distribución de education
education
Bachelor                252567
College                 102260
High School or Below     18915
Doctor                   17731
Master                   12287
Name: count, dtype: int64

### Distribución de marital_status
marital_status
Married     234845
Single      108153
Divorced     60762
Name: count, dtype: int64

### Distribución de loyalty_card
loyalty_card
Star      183745
Nova      136883
Aurora     83132
Name: count, dtype: int64

### Distribución de enrollment_type
enrollment_type
Standard          380419
2018 Promotion     23341
Name: count, dtype: int64

### Distribución de cancellation_year
cancellation_year
Activo    354110
2018       15519
2017       12147
2016       10248
2015        6360
2014        4344
2013        1032
Name: count, dtype: int64

### Distribución de cancellation_month
cancellation_month
Activo    354110
12          5112
11          5095
8           4992
7           4480
10          4322
9           4224
6           3960
1           3727
3           3579
5           3559
2           3336
4           3264
Name: count, dtype: int64

In [ ]:
for col in categorical_cols:
    print(f"\n### Porcentaje de {col}")
    print(df_history[col].value_counts(normalize=True, dropna=False) * 100)

In [ ]:
"""# Conteo de cancelaciones por mes (solo filas con cancelación)
canceladas = df_history[df_history['is_active'] == 0]
counts = canceladas['cancellation_month_name'].value_counts().sort_index()
pct = counts / counts.sum() * 100

# Crosstab mes vs año de cancelación (proporciones por mes)
ct = pd.crosstab(canceladas['cancellation_month_name'], canceladas['cancellation_year'], normalize='index')*100

# Chi-square (ejemplo)
from scipy.stats import chi2_contingency
table = pd.crosstab(canceladas['cancellation_month_name'], canceladas['some_category'])
chi2, p, dof, expected = chi2_contingency(table.fillna(0))